name: Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate activity graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          username: ismaelrdgdev
